services:
  - type: web
    name: quick-bistro-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn quick_bistro_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quick_bistro_backend.settings
      - key: SECRET_KEY
        value: your-secret-key
